[project]
name = "glm-asr-stt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate==1.12.0",
    "anyio==4.12.0",
    "audioop-lts==0.2.2",
    "audioread==3.1.0",
    "certifi==2025.11.12",
    "cffi==2.0.0",
    "charset-normalizer==3.4.4",
    "click==8.3.1",
    "customtkinter>=5.2.2",
    "decorator==5.2.1",
    "filelock==3.20.1",
    "fsspec==2025.12.0",
    "h11==0.16.0",
    "hf-xet==1.2.0",
    "httpcore==1.0.9",
    "httpx==0.28.1",
    "huggingface-hub==1.2.3",
    "idna==3.11",
    "jinja2==3.1.6",
    "joblib==1.5.3",
    "keyboard==0.13.5",
    "lazy-loader==0.4",
    "librosa==0.11.0",
    "llvmlite==0.46.0",
    "markupsafe==3.0.3",
    "mpmath==1.3.0",
    "msgpack==1.1.2",
    "networkx==3.6.1",
    "numba==0.63.1",
    "numpy==2.3.5",
    "opencc-python-reimplemented>=0.1.7",
    "packaging==25.0",
    "pillow>=12.0.0",
    "platformdirs==4.5.1",
    "pooch==1.8.2",
    "psutil==7.2.0",
    "pycparser==2.23",
    "pyperclip==1.11.0",
    "python-uinput==1.0.1",
    "pyyaml==6.0.3",
    "regex==2025.11.3",
    "requests==2.32.5",
    "safetensors==0.7.0",
    "scikit-learn==1.8.0",
    "scipy==1.16.3",
    "setuptools==80.9.0",
    "shellingham==1.5.4",
    "silero-vad>=6.2.0",
    "sounddevice==0.5.3",
    "soundfile==0.13.1",
    "soxr==1.0.0",
    "standard-aifc==3.13.0",
    "standard-chunk==3.13.0",
    "standard-sunau==3.13.0",
    "sympy==1.14.0",
    "threadpoolctl==3.6.0",
    "tokenizers==0.22.1",
    "tqdm==4.67.1",
    "transformers",
    "triton==3.5.1",
    "typer-slim==0.21.0",
    "typing-extensions==4.15.0",
    "urllib3==2.6.2",
]

[project.optional-dependencies]
cuda = [
    "torch==2.9.1",
    "torchaudio==2.9.1",
    "nvidia-cublas-cu12==12.8.4.1",
    "nvidia-cuda-cupti-cu12==12.8.90",
    "nvidia-cuda-nvrtc-cu12==12.8.93",
    "nvidia-cuda-runtime-cu12==12.8.90",
    "nvidia-cudnn-cu12==9.10.2.21",
    "nvidia-cufft-cu12==11.3.3.83",
    "nvidia-cufile-cu12==1.13.1.3",
    "nvidia-curand-cu12==10.3.9.90",
    "nvidia-cusolver-cu12==11.7.3.90",
    "nvidia-cusparse-cu12==12.5.8.93",
    "nvidia-cusparselt-cu12==0.7.1",
    "nvidia-nccl-cu12==2.27.5",
    "nvidia-nvjitlink-cu12==12.8.93",
    "nvidia-nvshmem-cu12==3.3.20",
    "nvidia-nvtx-cu12==12.8.90",
]

[tool.uv.sources]
transformers = { git = "https://github.com/huggingface/transformers", rev = "a7f29523361b2cc12e51c1f5133d95f122f6f45c" }
torch = { index = "pytorch-cu128" }
torchaudio = { index = "pytorch-cu128" }

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
